import { Color3 } from "@babylonjs/core";

export const SEQUENCE_PROFILES = {
  SSJ1: {
    label: "Ascendant I",
    buildupMs: 1800,
    burstMs: 300,
    landMs: 500,
    screechMs: 600,
    groundRockCount: 8,
    lightningStorms: 2,
    bloomPeak: 2.2,
    shakeMagnitude: 0.4,
    shakeRampUp: true,
    cameraZoomOut: 1.3,
    voiceId: "vo_goku_transform",
    colorFlash: new Color3(1.0, 0.95, 0.3),
    screenDistort: 0.4,
  },
  SSJ2: {
    label: "Ascendant II",
    buildupMs: 1400,
    burstMs: 250,
    landMs: 400,
    screechMs: 400,
    groundRockCount: 6,
    lightningStorms: 4,
    bloomPeak: 2.6,
    shakeMagnitude: 0.5,
    shakeRampUp: true,
    cameraZoomOut: 1.25,
    colorFlash: new Color3(1.0, 1.0, 0.5),
    screenDistort: 0.5,
  },
  SSJ3: {
    label: "Ascendant III",
    buildupMs: 3000,
    burstMs: 500,
    landMs: 700,
    screechMs: 1200,
    groundRockCount: 20,
    lightningStorms: 8,
    bloomPeak: 3.5,
    shakeMagnitude: 0.9,
    shakeRampUp: true,
    cameraZoomOut: 1.5,
    colorFlash: new Color3(1.0, 1.0, 0.7),
    screenDistort: 1.0,
  },
  SSB: {
    label: "Azure Ascendant",
    buildupMs: 1600,
    burstMs: 350,
    landMs: 500,
    screechMs: 500,
    groundRockCount: 10,
    lightningStorms: 3,
    bloomPeak: 2.8,
    shakeMagnitude: 0.55,
    shakeRampUp: false,
    cameraZoomOut: 1.35,
    colorFlash: new Color3(0.3, 0.7, 1.0),
    screenDistort: 0.8,
  },
  SSBE: {
    label: "Azure Overdrive",
    buildupMs: 2000,
    burstMs: 400,
    landMs: 600,
    screechMs: 700,
    groundRockCount: 14,
    lightningStorms: 5,
    bloomPeak: 3.2,
    shakeMagnitude: 0.7,
    shakeRampUp: false,
    cameraZoomOut: 1.4,
    colorFlash: new Color3(0.1, 0.5, 1.0),
    screenDistort: 1.0,
  },
  MYSTIC: {
    label: "Awakened Focus",
    buildupMs: 1200,
    burstMs: 280,
    landMs: 400,
    screechMs: 350,
    groundRockCount: 4,
    lightningStorms: 0,
    bloomPeak: 1.8,
    shakeMagnitude: 0.25,
    shakeRampUp: false,
    cameraZoomOut: 1.15,
    colorFlash: new Color3(0.9, 0.9, 1.0),
    screenDistort: 0.3,
  },
  ORANGE: {
    label: "Ember Giant",
    buildupMs: 1500,
    burstMs: 320,
    landMs: 450,
    screechMs: 450,
    groundRockCount: 10,
    lightningStorms: 0,
    bloomPeak: 2.4,
    shakeMagnitude: 0.45,
    shakeRampUp: true,
    cameraZoomOut: 1.3,
    colorFlash: new Color3(1.0, 0.45, 0.05),
    screenDistort: 0.6,
  },
  REVERT: {
    label: "Base Form",
    buildupMs: 400,
    burstMs: 200,
    landMs: 300,
    screechMs: 0,
    groundRockCount: 0,
    lightningStorms: 0,
    bloomPeak: 1.0,
    shakeMagnitude: 0.1,
    shakeRampUp: false,
    cameraZoomOut: 1.0,
    colorFlash: new Color3(0.7, 0.8, 1.0),
    screenDistort: 0,
  },
};

export const VOICE_MAP = {
  GOKU: { SSJ1: "vo_goku_transform", SSB: "vo_goku_transform" },
  VEGETA: { SSJ1: "vo_vegeta_transform", SSB: "vo_vegeta_transform" },
  GOHAN: { SSJ1: "vo_goku_transform", MYSTIC: "vo_goku_transform" },
  PICCOLO: { ORANGE: "vo_vegeta_transform" },
};
