export const COLLISION_LAYER = {
  NONE:        0x00,
  TERRAIN:     0x01,
  PLAYER:      0x02,
  PROJECTILE:  0x04,
  TRIGGER:     0x08,
  DESTRUCTIBLE:0x10,
  RAGDOLL:     0x20,
  ALL:         0xff,
} as const;

export type CollisionLayer = (typeof COLLISION_LAYER)[keyof typeof COLLISION_LAYER];

export const COLLISION_MASK = {
  TERRAIN:
    COLLISION_LAYER.PLAYER | COLLISION_LAYER.PROJECTILE | COLLISION_LAYER.DESTRUCTIBLE | COLLISION_LAYER.RAGDOLL,
  PLAYER:
    COLLISION_LAYER.TERRAIN | COLLISION_LAYER.PLAYER | COLLISION_LAYER.PROJECTILE | COLLISION_LAYER.DESTRUCTIBLE,
  PROJECTILE:
    COLLISION_LAYER.TERRAIN | COLLISION_LAYER.PLAYER | COLLISION_LAYER.DESTRUCTIBLE,
  TRIGGER:
    COLLISION_LAYER.PLAYER,
  DESTRUCTIBLE:
    COLLISION_LAYER.TERRAIN | COLLISION_LAYER.PLAYER | COLLISION_LAYER.PROJECTILE,
  RAGDOLL:
    COLLISION_LAYER.TERRAIN | COLLISION_LAYER.DESTRUCTIBLE,
} as const;

export type CollisionMaskKey = keyof typeof COLLISION_MASK;
